FROM golang:buster AS step_0
ENV CGO_ENABLED=0 GOOS=linux GOARCH=386 GO111MODULE=on
WORKDIR /root
COPY . .
RUN go generate
RUN go build -o /frontend

FROM scratch AS step_1
COPY --from=step_0 /frontend /
ENTRYPOINT ["/frontend"]
