FROM i386/debian:buster

LABEL Lan Tian "lantian@lantian.pub"
ENV GOOS=linux GOARCH=386
WORKDIR /root
COPY . .
RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y golang \
  && cd /root && go build -o /frontend \
  && cd / && rm -rf /root/* \
  && apt-get -qq purge -y golang \
  && apt-get -qq autoremove --purge -y && apt-get clean && rm -rf /var/lib/apt/lists

ENTRYPOINT ["/frontend"]
